version: '3.1'
services:
  jupyter-notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    image: melioconsulting/data-wrangling:latest
    volumes:
      - ./:/opt/app
    ports:
      - "10000:10000"
    command: jupyter lab --notebook-dir=/opt/app/ --ip="0.0.0.0" --port=10000 --no-browser --allow-root
    container_name: jupyterlab
